### ISSUE TITLE
Ambient music!

### ISSUE THREAD

**Issue by miner99213** [butmun/Interpost-Hague#128]
Lifeweb has carefully selected OST of dark ambient, wich contributes to the atmosphere greatly, creating sad and devastating atmosphere. I say we need the same thing, Ambient music would do wonders.

**Comment by diegoxt45** [comment]
https://www.youtube.com/watch?v=7uA98dgNQbE&t=4s

**Comment by mrpibb4201337** [comment]
thats not good ambiance diego

**Comment by diegoxt45** [comment]
yeah i took it for another round of lobby music sorry

**Comment by mrpibb4201337** [comment]
https://www.youtube.com/watch?v=pyuxz9R2XiY this could be good for maint since it sounds sort of like electrical noise with a constant thunk noise that slowly speeds up and then abruptly ends
https://www.youtube.com/watch?v=KEJM6IAdoic would be pretty good for general use, maybe its a little too song-like though

**Comment by Muncher2112** [comment]
From @Zangeiti music pack


[Extra Ambient.zip](https://github.com/butmun/InterHippie2/files/4315261/Extra.Ambient.zip)

**Comment by mrpibb4201337** [comment]
https://www.youtube.com/watch?v=UsWChncYIdg this sounds like the ambiance from E.Y.E. up until 3:26 and that means its good and we should use it liberally
https://www.youtube.com/watch?v=1TZ2fqjQtxE good ambient track for whatever

**Comment by SireTurret** [comment]
Send me the .ogg's in coder channel.

**Comment by SireTurret** [comment]
Slowly being added. I'll change the ambient system later too to ALWAYS play the certain ambient in parts of the station.
